# Site settings
title: 順の理想郷
SEOTitle: SenaJun Blog - ゴミ箱
header-img: img/65497494_p0.png
email: adsjkqwsad@gmail.com
description: "大切な人と、何時かまだ巡り会えますように。"
keyword: "SenaJun, ブログ, 順の理想乡, 理想郷, 理想乡, 瀬名順, 濑名顺"
url: "http://SenaJun.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/SenaJun/SenaJun.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "大切な人と、<br>何時かまだ巡り会えますように。"
sidebar-avatar: /img/apple-touch-icon.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     
github_username:    SenaJun
facebook_username:  
Telegram_username:   SenaJun
twitter_username:   SenaJun_CN




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: senajun

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: SenaJun.github.io    #仓库名称
  owner: SenaJun    #github用户名
  admin: SenaJun
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 8bbb5e955b3d37e76dbc449c270242df

# Google Analytics
ga_track_id: 'UA-139989416-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: ture                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Haor",
        href: "https://haor233.com/author/haor/"
    },{
        title: "zjyl1994 の 自留地",
        href: "https://blog.zjyl1994.com/"
    }
]
